### ISSUE TITLE
Data has issues

### ISSUE THREAD

**Issue by rjiang9** [CanDIG/mohccn-synthetic-data#9]
Hi Marion, 

When I tried to run to convert the Large/Extra dataset, I actually got validation errors:

```
Traceback (most recent call last):
  File "/Users/ray.jiang/projects/CANDIG/./clinical_ETL/src/clinical_etl/CSVConvert.py", line 814, in <module>
    main()
  File "/Users/ray.jiang/projects/CANDIG/./clinical_ETL/src/clinical_etl/CSVConvert.py", line 803, in main
    packets, errors = csv_convert(input_path, manifest_file, minify=args.minify, index_output=args.index,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray.jiang/projects/CANDIG/./clinical_ETL/src/clinical_etl/CSVConvert.py", line 759, in csv_convert
    schema.validate_ingest_map(result)
  File "/Users/ray.jiang/projects/CANDIG/clinical_ETL/src/clinical_etl/schema.py", line 335, in validate_ingest_map
    self.validate_schema(root_schema, map_json[root_schema][x])
  File "/Users/ray.jiang/projects/CANDIG/clinical_ETL/src/clinical_etl/schema.py", line 430, in validate_schema
    self.validate_schema(ns, map_json[ns][x])
  File "/Users/ray.jiang/projects/CANDIG/clinical_ETL/src/clinical_etl/schema.py", line 421, in validate_schema
    eval(f"self.validate_{schema_name}({map_json})")
  File "<string>", line 1, in <module>
  File "/Users/ray.jiang/projects/CANDIG/clinical_ETL/src/clinical_etl/mohschemav3.py", line 473, in validate_comorbidities
    if f in self.validation_schema["comorbities"]["required_fields"]:
            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'comorbities'
```
Screenshot is like this:

![image](https://github.com/user-attachments/assets/df16346c-6cb9-4b41-ba58-a20013a38380)
 
I wonder whether the data is all good on your end. @mshadbolt 

Thanks,
Ray

**Comment by mshadbolt** [comment]
Hi Ray, not sure what is happening but I don't get the same errors when I try to convert the data.

The best way to convert the data is to clone the repo: https://github.com/CanDIG/mohccn-synthetic-data

Install requirements then run the following command inside the repo

```
python src/csv_to_ingest.py --size l
```
or xs etc. 

This is currently working for me.

**Comment by rjiang9** [comment]
Thank you @mshadbolt  for looking into it. 

It's working just fine by using the tool of csv_to_ingest.py from this repo as you mentioned only with some warnings. I thought it should also work by using the CSVConvert.py tool, since here we have raw data, mappings and manifest.yml. I may get this dataset wrong. 

Thank you again and have a great weekend,
Ray
